---

- name: HTCondor 스케쥴러 데몬 상태를 확인합니다.
  ansible.builtin.systemd:
    name: "condor.service"
  register: condor_service_status

- name: 스케쥴러 데몬의 상태가 정상이 아니라면 상태를 출력합니다.
  debug:
    var: condor_service_status
  when:
    - condor_service_status.status.ActiveState != "active"

- name: HTCondor 클러스터의 CentralManager의 Negotiator 데몬과 통신여부를 확인합니다.
  ansible.builtin.shell:
    cmd: "condor_ping -type negotiator"
  register: condor_negotiator_status

- name: 통신이 불가능하다면 결과를 보고합니다.
  debug:
    var: condor_negotiator_status
  when:
    - condor_negotiator_status.rc != 0

- name: 테스트 결과를 기록합니다.
  ansible.utils.update_fact:
    updates:
      - path: check_results.batch
        value: true
  when:
    - condor_service_status.status.ActiveState == "active"
    - condor_negotiator_status.rc == 0
  register: updated

- name: Save the result for the batch test
  ansible.builtin.set_fact:
    check_results: "{{ updated.check_results }}"
  when:
    - updated.changed

